export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const USER_UPDATE_URL = 'USER_UPDATE_URL';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_USER = 'UPDATE_USER';

export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCTS_FAIL';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const CLEAR_CURRENT_PRODUCT = 'CLEAR_CURRENT_PRODUCT';

export const NEW_CATEGORY_SUCCESS = 'NEW_CATEGORY_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CATEGORY_FAIL = 'CATEGORIES_FAIL';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';
export const CLEAR_CURRENT_CATEGORY = 'CLEAR_CURRENT_CATEGORY';

export const NEW_RATING_SUCCESS = 'NEW_RATING_SUCCESS';
export const GET_RATINGS_SUCCESS = 'GET_RATINGS_SUCCESS';
export const GET_RATING_BY_PRODUCT = 'GET_RATING_BY_PRODUCT';
export const RATING_FAIL = 'RATINGS_FAIL';
export const UPDATE_RATING = 'UPDATE_RATING';
export const RATING_DELETE = 'RATING_DELETE';
export const GET_RATING_BY_ID = 'GET_RATING_BY_ID';
export const CLEAR_RATINGS = 'CLEAR_RATINGS';
export const CLEAR_CURRENT_RATING = 'CLEAR_CURRENT_RATING';
export const CLEAR_RATINGS_BY_PRODUCT = 'CLEAR_RATINGS_BY_PRODUCT';


export const NEW_CART_SUCCESS = 'NEW_CART_SUCCESS';
export const GET_CARTS_SUCCESS = 'GET_CARTS_SUCCESS';
export const GET_CARTS_BY_USER_SUCCESS = 'GET_CARTS_BY_USER_SUCCESS';
export const CART_FAIL = 'CARTS_FAIL';
export const UPDATE_CART = 'UPDATE_CART';
export const CART_DELETE = 'CART_DELETE';
export const GET_CART_BY_ID = 'GET_CART_BY_ID';
export const CLEAR_CARTS = 'CLEAR_CARTS';
export const CLEAR_CURRENT_CART = 'CLEAR_CURRENT_CART';


export const NEW_ORDER_SUCCESS = 'NEW_ORDER_SUCCESS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const ORDER_FAIL = 'ORDERS_FAIL';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const ORDER_DELETE = 'ORDER_DELETE';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const CLEAR_CURRENT_ORDER = 'CLEAR_CURRENT_ORDER';
